@startuml
class 系统用户 {
 -用户ID
 -用户名
 -密码
 - login()
 - 退出()
}
class 图书管理员 {
 -用户ID
 -用户名
 -密码
 - login()
 - 退出()
 -借出图书()
 -维护书目()
 -归还图书()
 -读者管理()
}
class 读者 {
 -用户ID
 -用户名
 -密码
 -借书卡号
 -已借图书
 -限额图书数
 - login()
 - 退出()
 - 借书()
 - 还书()
 - 查询()
 - 预定图书()
 - 取消预订()
}
class 书库资源品种{
 资源名称
 国际出版号
 价格
 简介
 馆藏数
 可借数
 - 修改图书信息()
 - 添加图书()
 - 减少图书()
}
class 图书品种{
    作者
    出版社
    出版日期
    - 修改信息()
    - 新增()
    - 减少()

}
class 借还记录{
    借书日期
    归还日期
 - 查询记录()
 - 新增记录()
}
class 还书超时罚款{
    逾期时间
    罚款金额
    - 计算罚款金额()
    - 记录罚款信息()
}
class 资源项{
    馆藏流水号
    状态
}
class 预定记录{
    预定日期
    - 记录预定信息()
    - 预定通知()
}
class 查询书目{
    图书品种
    图书名
    图书编号
    - 根据品种查询()
    - 根据书名查询()
    - 根据编号查询()
}
系统用户<|--图书管理员
系统用户<|--读者
书库资源品种<|--图书品种
借还记录  -- 读者
借还记录 "*"--"1"图书管理员
借还记录 "1"--"*"还书超时罚款
书库资源品种"1"*--"*"资源项:拥有
借还记录"*"--"1"资源项
预定记录"*"--"1"读者
预定记录"*"--"1"书库资源品种
查询书目"*"--"1"读者
查询书目"*"--"1"书库资源品种
@enduml