@startuml
left to right direction
actor 读者
rectangle 图书管理{
    图书管理员-->(管理员登录)
    图书管理员-->(借出图书)
    图书管理员-->(归还图书)
    图书管理员-->(维护书目)
    图书管理员-->(维护读者信息)
    图书管理员-->(读者管理)
    (登记赔偿).>(归还图书):《extend》
    (找回密码).>(管理员登录):《extend》
    读者-->(登录)
    读者-->(查询书目)
    读者-->(查询借阅情况)
    读者-->(预定图书)
    读者-->(取消预订)
    读者-->(借书)
    读者-->(还书)
    (找回密码).>(登录):《extend》
    (续借).>(借书):《extend》
    (缴纳罚金).>(还书):《extend》
}
@enduml